### ISSUE TITLE
Dependency Management Automation

### ISSUE THREAD

**Issue by aorinevo** [NerdWalletOSS/shepherd#111]
## Narrative

As a maintainer of Shepherd, I want a quick and easy way to keep dependencies up-to-date.

## Proposed Change

The proposed change is to integrate renovate, renovate approve, semantic commits, and semantic-releases.  

With the right combination of settings across these four Github apps, CI/CD can take care of updating minor and patch dependencies (relative to the semantic commit message), approve and merge the corresponding PRs, and finally publish a new tag version with auto-updates to changelog.

## ROI
- near _real time_ vulnerability and security patches
- reduced overhead for maintainers

## DependaBot vs RenovateBot

| |  DependaBot | RenovateBot |
|----|----|----|
|post install config (i.e. run `npm dedupe`) | No | Yes |
|price | Free | Free |

## Notes
- Shepherd currently uses dependabot (see https://dependabot.com)
- Renovate Approve (see https://github.com/apps/renovate-approve)
- Renovate (see https://github.com/marketplace/renovate)
- Semantic Release (see https://github.com/semantic-release/github)
- Semantic Pull Requests (see https://github.com/zeke/semantic-pull-requests)

**Comment by parshap** [comment]
I’m super on board with semantic-release. The commit message requirements can be kind of burdensome for those not familiar, but the release process is _much_ better than the semi-manual one we have now (docs here: https://github.com/NerdWalletOSS/shepherd/blob/master/docs/releasing.md).

Renovate and Dependabot, I’m less familiar with. Can you speak to the benefits of Renovate over what we already have?

Also would love any input from @nwalters512 or anyone else watching.

**Comment by aorinevo** [comment]
PR: https://github.com/NerdWalletOSS/shepherd/pull/114

**Comment by aorinevo** [comment]
Previously, pricing was one of the main differentiators, but since the acquisition of Dependabot by GitHub [1] and RenovateBot by Whitesource [2], both are now free of charge.  Either product will satisfy our business needs.

It's worth noting that there is low risk of vendor lock-in in going with either as both require a low-level of integration and both a configuration driven.

Lastly, it would be helpful to know what automation tooling for dependency management NerdWallet currently use in other projects?  I'd be less inclined to introduce a new tool that closely mirrors what is already widely used internally - that adds unnecessary operational complexity and maintenance costs by way of developer time.

## References
1. https://dependabot.com/blog/hello-github/
2. https://resources.whitesourcesoftware.com/news-whitesource/renovate-an-open-source-project-for-software-dependency-updates-joins-the-whitesource-family

**Comment by parshap** [comment]
Thanks for the context! We're starting to experiment with both Snyk and Dependabot internally, but neither are a huge part of our workflow right now.

Since Depndabot seems to already be enabled in here (not sure if we even explicitly did that or if GitHub just enabled it everywhere), is there a benefit to switching to Renovate?

**Comment by aorinevo** [comment]
## Status update
### Tasks completed
Completed integration of
- semantic-release
- semantic-pull-requests

### Remaining Items
- integrate with Renovate or DependaBot

### Extras
- Added WIP GItHub app to prevent merges when `WIP` is present in the PR title.

**Comment by aorinevo** [comment]
> Thanks for the context! We're starting to experiment with both Snyk and Dependabot internally, but neither are a huge part of our workflow right now.
> 
> Since Depndabot seems to already be enabled in here (not sure if we even explicitly did that or if GitHub just enabled it everywhere), is there a benefit to switching to Renovate?

I got DependaBot working but it seems extremely limited. Here is a short list of the things I'm struggling with:
- specifying times and days on which to run checks (i.e. M,W,F between 10am-2am)
- customizing PR titles

I'm also not a fan of some of the UX within Dependabot PRs.  For example, to rebase you have to comment `@dependabot rebase` compared to clicking checkbox on a Renovate PR.

It could be that I am just not that familiar with this tool but at this point I'm advocating for switching to Renovate.

**Comment by parshap** [comment]
No objection to switching to Renovate from me if Depndabot isn't working out great.

**Comment by aorinevo** [comment]
This issue is resolved as of v1.7.0+.

Dependabot is in a working state.  Let's hold off on switching to Renovate.
