### ISSUE TITLE
Handle applying migrations multiple times

### ISSUE THREAD

**Issue by nwalters512** [NerdWalletOSS/shepherd#3]
We have two options here:

 - Assume migrations are idempotent (hard)
 - Before applying, remove all commits from branch and start over, and then force-push new commits to branch

The second option is easier and more robust, which is what I'm inclined to go with. However, it introduces the problem of potentially overwriting manual human work on the branch. To get around that, we should pull any changes from the remote and then check if any are not prefixed with `[shepherd]`, which we'll assume means they were made by a human. If we find any, we can either skip that repo entirely or leave a message on the PR. We should also document exactly how this works.

**Comment by parshap** [comment]
I believe this use case is handled now with the new pushing logic and flags. See #37.
