### ISSUE TITLE
Improve authentication with GitHub API

### ISSUE THREAD

**Issue by nwalters512** [NerdWalletOSS/shepherd#38]
Currently, we rely on either a `.netrc` configuration or a `GITHUB_TOKEN` environment variable for GitHub API authentication. We could take some pages out of the `hub` command and allow people to provide their username/password on the CLI, generate a token for them, and persist it for future use.

Relevant: https://hub.github.com/hub.1.html

**Comment by aorinevo** [comment]
I believe this issue has been resolved.  If not, feel free to reopen.

**Comment by aorinevo** [comment]
I believe this issue has been resolved. If not, feel free to reopen.
