### ISSUE TITLE
Github incomplete search results notification

### ISSUE THREAD

**Issue by danpilch** [NerdWalletOSS/shepherd#401]
Shepherd currently does not provide a way to fail or warn that a github api search is incomplete. 

see: https://docs.github.com/en/github/searching-for-information-on-github/troubleshooting-search-queries#potential-timeouts

It would be useful if shepherd could warn or fail if a github search is incomplete

I have created a PR that provides a warning to the user if the search is incomplete and a flag shepherd checkout `--fail-on-incomplete-search` migration to fail the migration.

see: https://github.com/NerdWalletOSS/shepherd/pull/324

**Comment by aorinevo** [comment]
Definitely seems like important information a shepherd user should have visibility into (i.e. As a shepherd user, I want to know when a search is incomplete so that I can ensure I don't accidentally only open PRs for some strict subset of targeted repos).

I'll take the PR for a spin later today.
