### ISSUE TITLE
Update docs: Remove Travis CI, Add GitHub Actions

### ISSUE THREAD

**Issue by aorinevo** [NerdWalletOSS/shepherd#500]
## Summary

We recently switched over from Travis CI to GitHub actions but the documentation still references Travis CI.  The purpose of this ticket and corresponding PR is to remove references to Travis CI and add documentation for GitHub actions.

**Comment by uniyalmani** [comment]
sir i have Updated CI/CD from Travis CI to GitHub Actions in documentation.

**Comment by aorinevo** [comment]
Closed by #636
