### ISSUE TITLE
Add support for labels

### ISSUE THREAD

**Issue by ghost** [NerdWalletOSS/shepherd#590]
It would be handy to be able to add labels (where supported) to PRs as part of this process.

**Comment by sdann** [comment]
This looks to be a duplicate of issue https://github.com/NerdWalletOSS/shepherd/issues/54

**Comment by aorinevo** [comment]
> This looks to be a duplicate of issue https://github.com/NerdWalletOSS/shepherd/issues/54

Yep, these seem to be the same.

**Comment by aorinevo** [comment]
Closing in favor of #54
