### ISSUE TITLE
Update master branch to main

### ISSUE THREAD

**Issue by aorinevo** [NerdWalletOSS/shepherd#651]
The rationale for renaming the "master" branch to "main" stems primarily from a desire to use more inclusive language.

**Comment by aorinevo** [comment]
@luislew, any concern in updating the branch name?  I'm not sure if NerdWallet is dependent on it or is making use of the default branch property.

**Comment by luislew** [comment]
No concerns - _internally_ at NerdWallet we are in the process of moving from `master` to `main` but have some dependencies on our internal tooling. This repo doesn't depend on any of that and should be free to move 👍🏻

**Comment by aorinevo** [comment]
Updated branch name.
