### ISSUE TITLE
Add GitHub Enterprise Cloud Support

### ISSUE THREAD

**Issue by aorinevo** [NerdWalletOSS/shepherd#671]
## Background

Support for GitHub Enterprise was released in v2 of Shepherd, however, GitHub Enterprise comes in two flavors: Server and Cloud.  We released support for Server but not Cloud.  

The scope of this issue is to add support for GitHub Enterprise Cloud.

**Comment by kavitha186** [comment]
If the Shepherd github enterprise url is not set in the env var, it picks up api.github.com const shepherdGitHubEnterpriseUrl = SHEPHERD_GITHUB_ENTERPRISE_URL || 'api.github.com'; as per the current impl.

**Comment by aorinevo** [comment]
Yes, that’s correct but won’t suffice for the cloud use case as the api call needs to include cloud path (e.g., /enterprises/iheartradio).

**Comment by aorinevo** [comment]
Completed in v2.
