### ISSUE TITLE
Non-master branches

### ISSUE THREAD

**Issue by agolomoodysaada** [NerdWalletOSS/shepherd#85]
Several repos in our org do not rely on master being the source of truth...
Is there a way to make a custom branch name the default? 
Is it possible to make the branch name to be dynamically decided before checkout based on the repo name or based on a shell command?

We would like to use Shepherd to standardize master as the main branch. But we need a mechanism like described above to help us get there step by step.

**Comment by alchar** [comment]
Should be addressed by https://github.com/NerdWalletOSS/shepherd/pull/81?

**Comment by parshap** [comment]
@agolomoodysaada can you describe in more detail what you're trying to do and what issue you're running in to? Shepherd [doesn't make any assumptions](https://github.com/NerdWalletOSS/shepherd/search?utf8=%E2%9C%93&q=master&type=) about the default branch being `master`.

**Comment by parshap** [comment]
Going to close this issue as I believe non-master branches are already supported. Please re-open this if you think any new functionality is needed.

**Comment by parshap** [comment]
Related: #71 and #72
