### ISSUE TITLE
Using deprecated auth method

### ISSUE THREAD

**Issue by carlpett** [NerdWalletOSS/shepherd#99]
Hi!
It seems shepherd is using the auth method Github is in process of deprecating: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param (I get an email from Github about using it when running shepherd).
Is there some dependency you need to bump, or is this in shepherd itself?

**Comment by nwalters512** [comment]
Good catch! This is indeed Shepherd's fault. The way we do auth with the `@octokit/rest` client is now deprecated: https://github.com/octokit/rest.js/issues/1588. This should be a pretty straightforward fix - feel free to open up a PR, or let us know if you won't have the bandwidth for that and we can take care of it!

**Comment by aorinevo** [comment]
Hi @carlpett and @nwalters512, happy to help resolve this issue but currently side-tracked with tackling shepherd vulnerabilities through dependency management for which I've opened and started work on the following issue https://github.com/NerdWalletOSS/shepherd/issues/103.

**Comment by aorinevo** [comment]
I believe this has been addressed.  If not, feel free to reopen.
